#!/bin/bash

source /u/cs241/setup

if [ $# -ne 2 ]; then
	echo "Tester expects 2 arguments: testasm asm.rkt tests.txt"
	exit 1
fi

ASM=$1
TESTS=$2

mkdir -p testdata



for var in `cat $2`
do 
	if [ -f "${var}" ]
		then
			if [ -e "${var}.out" ]; then
				rm "${var}.out"
			fi
			if [ -e "${var}.expect" ]; then
				rm "${var}.expect"
			fi
			
			echo "= Assembling ${var} ="
			unset output
			unset expect
			unset error
			output=`mktemp -p /tmp`
			expect=`mktemp -p /tmp`
			
			xxdoutput="${var}.out"
			xxdexpect="${var}.expect"
			error="${var}.error"
			
			java cs241.binasm < ${var} > ${expect}
			if [ ${ASM} == "asm.rkt" ] 
				then
					racket asm.rkt < ${var} > ${output} 2> ${error}
				else
					./${ASM} < ${var} > ${output}
			fi
			
			xxd -cols 4 ${output} > ${xxdoutput}
			xxd -cols 4 ${expect} > ${xxdexpect}

			result=`cmp  ${xxdoutput} ${xxdexpect}`
			if [ "${result}" == "" ]
				then	
					mv ${xxdoutput} "testdata/${xxdoutput}"
					mv ${xxdexpect} "testdata/${xxdexpect}"
					mv ${error} "testdata/${error}"
			else
				echo "   ${result}"
			fi
			
		else 
			echo "Expected input file ${var} not found. Test aborted."
	fi
done	
		